gerbers:
	kikit fab jlcpcb --assembly --schematic badgeCarrierCard.kicad_sch badgeCarrierCard.kicad_pcb production
pdf:
	kicad-cli sch export pdf --output pdfs/schematic.pdf badgeCarrierCard.kicad_sch
