workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

stages:
  - drc
  - production
  - schematic

# Cache configuration
.cache_template: &cache_template
  cache:
    key: pycache
    paths:
      - .venv
    policy: pull-push


.env_template: &env_template
  image: kicad/kicad:9.0
  <<: *cache_template
  before_script:
    - apt-get -qq update -o APT::Get::List-Cleanup="0"
    - apt-get -qq install -y python3-venv python3-pip make &> /dev/null
    - make prepare

# DRC jobs
drc_carrier:
  stage: drc
  <<: *env_template
  script:
    - make drc_carrier

drc_m2:
  stage: drc
  <<: *env_template
  script:
    - make drc_m2

# Gerber jobs
gerbers_carrier:
  stage: production
  <<: *env_template
  needs:
    - drc_carrier
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - make gerbers_carrier
    - make pdfs_carrier
  artifacts:
    paths:
      - ./Carrier/production/
      - ./Carrier/pdfs/
    expire_in: 1 month

gerbers_m2:
  stage: production
  <<: *env_template
  needs:
    - drc_m2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - make gerbers_m2
    - make pdfs_m2
  artifacts:
    paths:
      - ./M2/production/
      - ./M2/pdfs/
    expire_in: 1 month

# Schematic jobs
schematic_carrier:
  stage: schematic
  <<: *env_template
  needs:
    - gerbers_carrier
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - make schematic_carrier
  artifacts:
    paths:
      - ./Carrier/pdfs/schematic.pdf
    expire_in: 1 month

schematic_m2:
  stage: schematic
  <<: *env_template
  needs:
    - gerbers_m2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - make schematic_m2
  artifacts:
    paths:
      - ./M2/pdfs/schematic.pdf
    expire_in: 1 month
