M48
; DRILL file {KiCad 9.0.0+1} date 2025-04-14T19:52:18+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T19:52:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X142.15Y-100.21
X142.15Y-105.99
T2
X153.3Y-88.1
X153.3Y-98.1
M30
